name: urlshortener

services:
  rest-api:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_URL: mongodb://mongodb/UrlShortener

  mongodb:
    image: mongo:8.0.0-rc4-jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - UrlShortener:/data/db

  mongodb-viewer:
    image: mongo-express:1.0.2-18-alpine3.19
    restart: always
    ports:
      - "8084:8081"
    links:
      - "mongodb:mongo"

volumes:
  UrlShortener: